version: '3'

services:

  db:
    image: mysql:5.7
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=order-car-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    volumes:
      - /usr/app/order-car-db:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 6000:8080
